name: Build with graphviz

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - name: install graphviz
        run: sudo apt-get install graphviz
      - name: build the docs
        run: make
      - uses: EndBug/add-and-commit@v7
        with:
          add: "./"
          author_name: ff6347Bot
          author_email: dev@ff6347.email
